# .streamlit/theme.toml

[theme]
primaryColor = "#BEBEBC"  # Grey for primary elements like buttons and headers
backgroundColor = "#94806B"  #brown
secondaryBackgroundColor = "#D4C9BA"  # beige
textColor = "#94806B"  # brown
